name: bezique # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary:  A 19th-century French melding and trick-taking card game for two players
description: |
   A two-handed Bezique pack is a 64-card pack, consisting of the ace down to the seven of each suit doubled (i.e. the twos to sixes are stripped from two packs and the remaining cards combined), The players cut for deal, with the highest card having preference. The rank of the cards in cutting, and in play, is A, 10, K, Q, J, 9, 8 and 7. Eight cards are dealt in batches of three, two and three, to each player with the next card being placed face up between the two players to establish the trump suit. The remaining cards, known as the "talon" or "stock", are placed face down beside it. Should the turn-up card be a 7 the dealer scores ten.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  bezique_icon.png
title: bezique

apps:
  bezique:
    command: bezique
parts:
  bezique:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      bezique: build/
      bezique.1: man/man1/

architectures:
  - build-on: amd64

